name: flutter_modular_mobx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.2.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_modular: ^4.0.1+2
  flutter_speed_dial: ^4.4.0+1
  flutter_staggered_grid_view: ^0.4.0
  mobx: ^2.0.4
  path_provider: ^2.0.5
  provider: ^6.0.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: any

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
