name: flutter_modular_mobx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.2.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_modular: ^4.0.1+2
  flutter_speed_dial: ^4.4.0+1
  flutter_staggered_grid_view: ^0.4.0
  mobx: ^2.0.4
  path_provider: ^2.0.5
  provider: ^6.0.1
  
  shared_preferences: any

  #slidy: ^3.2.2+1
  adaptive_theme: ^2.2.0
  validators: ^3.0.0
  connectivity: ^3.0.6

  pull_to_refresh: ^2.0.0


dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: any

  flutter_lints: ^1.0.0



flutter:

  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/images/
    - assets/translations/

